# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
BOARD_TAG     = mega
BOARD_SUB     = atmega2560
MONITOR_PORT  = /dev/ttyUSB*

ARDMK_DIR     = mk
ARDUINO_DIR   = /usr/share/arduino
ARDUINO_DIR   = /usr/lib/arduino
USER_LIB_PATH = thirdparty
ARDUINO_LIBS  = Wire SPI FastLED basicMPU6050 

include $(ARDMK_DIR)/Arduino.mk

